name: rag-demo
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy>=1.21.0
  - pandas>=1.3.0
  - scipy>=1.7.0
  - scikit-learn>=1.3.0
  - matplotlib>=3.5.0
  - pillow>=8.3.0
  - pyyaml>=6.0
  - pytest>=7.0.0
  - ruff>=0.4.0
  - black>=24.0.0
  - pip:
    # NLP and Text Processing
    - nltk>=3.6
    - tiktoken>=0.4.0
    # Machine Learning & Embeddings
    - sentence-transformers>=2.2.0
    - transformers>=4.20.0
    # API Integrations
    - openai>=1.0.0
    # Graph Processing
    - networkx>=2.8.0
    # Configuration & Utilities
    - python-dotenv>=0.19.0
    # Visualization
    - plotly>=5.10.0